/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Grocery_Delivery_Application;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
